#!/bin/python

import jinja2
import yaml
import logging
from subprocess import call

RED = '\033[91m'
GREEN = '\033[92m'
BLUE = '\033[94m'
ENDC = '\033[0m'

def renderTemplate(searchpath, template_file, template_vars):
    templateLoader = jinja2.FileSystemLoader( searchpath=searchpath )
    templateEnv = jinja2.Environment( loader=templateLoader )
    template = templateEnv.get_template( template_file )
    content = template.render( template_vars )
    return content

if __name__ == "__main__":
    try:
        with open("scenarios.yml", "r") as f:
            data = yaml.load(f)
    except IOError as e:
        logging.error("Unable to find scenarios.yml. Exiting due to %s" % e)
        exit(1)

    for scenario in data["scenarios"]:
        vars = {
            "containers": filter(lambda l: l["name"] in scenario["containers"], data["containers"]),
            "vars": scenario["vars"],
            "playbook": "" if "playbook" not in scenario else scenario["playbook"],
        }

        output = renderTemplate(".", "molecule.yml.j2", vars)
        # yaml formatting
        output = yaml.load(output)
        with open("molecule.yml", "w") as f:
             yaml.dump(output, f, default_flow_style=False)

        rc = call("molecule test", shell=True)
        print "RC: %s" % rc
