'\" t
.\"     Title: atomic-openshift-installer
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 12/28/2016
.\"    Manual: atomic-openshift-installer
.\"    Source: atomic-openshift-utils 1.4
.\"  Language: English
.\"
.TH "ATOMIC\-OPENSHIFT\-I" "1" "12/28/2016" "atomic\-openshift\-utils 1\&.4" "atomic\-openshift\-installer"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
atomic-openshift-installer \- Interactive OpenShift Container Platform (OCP) installer
.SH "SYNOPSIS"
.sp
atomic\-openshift\-installer [OPTIONS] COMMAND [OPTS]
.SH "DESCRIPTION"
.sp
\fBatomic\-openshift\-installer\fR makes the process for installing OCP easier by interactively gathering the data needed to run on each host\&. It can also be run in unattended mode if provided with a configuration file\&.
.SH "OPTIONS"
.sp
The following options are common to all commands\&.
.PP
\fB\-u\fR, \fB\-\-unattended\fR
.RS 4
Run installer in
\fBunattended\fR
mode\&. You will not be prompted to answer any questions\&.
.RE
.PP
\fB\-c\fR, \fB\-\-configuration\fR \fIPATH\fR
.RS 4
Provide an alternate
\fIPATH\fR
to an
\fIinstaller\&.cfg\&.yml\fR
file\&.
.RE
.PP
\fB\-a\fR \fIDIRECTORY\fR, \fB\-\-ansible\-playbook\-directory\fR \fIDIRECTORY\fR
.RS 4
Manually set the
\fIDIRECTORY\fR
in which to look for Ansible playbooks\&.
.RE
.PP
\fB\-\-ansible\-log\-path\fR \fIPATH\fR
.RS 4
Specify the
\fIPATH\fR
of the directory in which to save Ansible logs\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Run the installer with more verbosity\&.
.RE
.PP
\fB\-d\fR, \fB\-\-debug\fR
.RS 4
Enable installer debugging\&. Logs are saved in
\fI/tmp/installer\&.txt\fR\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show the usage help and exit\&.
.RE
.SH "COMMANDS"
.sp
\fBatomic\-openshift\-installer\fR has four modes of operation:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBinstall\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBuninstall\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBupgrade\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fBscaleup\fR
.RE
.sp
The options specific to each command are described in the following sections\&.
.SH "INSTALL"
.sp
The \fBinstall\fR command will guide you through steps required to install an OCP cluster\&. After all of the required information has been collected (target hosts, storage options, high\-availability), the installation will begin\&.
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
Forces an installation\&. This means that hosts with existing installations will be reinstalled if required\&.
.RE
.PP
\fB\-\-gen\-inventory\fR
.RS 4
Generate an Ansible inventory file and exit\&. The default location for the inventory file is
\fI~/\&.config/openshift/hosts\fR\&.
.RE
.SH "UNINSTALL"
.sp
The \fBuninstall\fR command will uninstall OCP from your target hosts\&. This command has no additional options\&.
.SH "UPGRADE"
.sp
The \fBupgrade\fR command will upgrade a cluster of hosts to a newer version of OCP\&.
.PP
\fB\-l\fR, \fB\-\-latest\-minor\fR
.RS 4
Upgrade to the latest minor version\&. For example, if you are running version
\fB3\&.2\&.1\fR
then this could upgrade you to
\fB3\&.2\&.2\fR\&.
.RE
.PP
\fB\-n\fR, \fB\-\-next\-major\fR
.RS 4
Upgrade to the latest major version\&. For example, if you are running version
\fB3\&.2\fR
then this could upgrade you to
\fB3\&.3\fR\&.
.RE
.SH "SCALEUP"
.sp
The \fBscaleup\fR command is used to add new nodes to an existing cluster\&. This command has no additional options\&.
.SH "FILES"
.sp
\fB~/\&.config/openshift/installer\&.cfg\&.yml\fR \(em Installer configuration file\&. Can be used to generate an inventory later or start an unattended installation\&.
.sp
\fB~/\&.config/openshift/hosts\fR \(em Generated Ansible inventory file\&. Used to run the Ansible playbooks for install, uninstall, and upgrades\&.
.sp
\fB/tmp/ansible\&.log\fR \(em The default location of the ansible log file\&.
.sp
\fB/tmp/installer\&.txt\fR \(em The location of the log file for debugging the installer\&.
.SH "AUTHOR"
.sp
Red Hat OpenShift Productization team
.sp
For a complete list of contributors, please visit the GitHub charts page\&.
.SH "COPYRIGHT"
.sp
Copyright \(co 2016 Red Hat, Inc\&.
.sp
\fBatomic\-openshift\-installer\fR is released under the terms of the ASL 2\&.0 license\&.
.SH "SEE ALSO"
.sp
\fBansible\fR(1), \fBansible\-playbook\fR(1)
.sp
\fBThe openshift\-ansible GitHub Project\fR \(em https://github\&.com/openshift/openshift\-ansible/
.sp
\fBThe atomic\-openshift\-installer Documentation\fR \(em https://docs\&.openshift\&.com/container\-platform/3\&.3/install_config/install/quick_install\&.html
