= openshift-ansible Style Guide

The purpose of this guide is to describe the preferred coding conventions used in this repository (both in ansible and python).

It is important to note that this repository may not currently comply with all style guide rules, but the intention is that it will.

All new pull requests created against this repository MUST comply with this guide.

This style guide complies with https://www.ietf.org/rfc/rfc2119.txt[RFC2119].

== Python


=== Python Maximum Line Length

.Context:
* https://www.python.org/dev/peps/pep-0008/#maximum-line-length[Python Pep8 Line Length]

'''
[[All-lines-SHOULD-be-no-longer-than-80-characters]]
[cols="2v,v"]
|===
| <<All-lines-SHOULD-be-no-longer-than-80-characters, Rule>>
| All lines SHOULD be no longer than 80 characters.
|===

Every attempt SHOULD be made to comply with this soft line length limit, and only when it makes the code more readable should this be violated.

Code readability is subjective, therefore pull-requests SHOULD still be merged, even if they violate this soft limit as it is up to the individual contributor to determine if they should violate the 80 character soft limit.


'''
[[All-lines-MUST-be-no-longer-than-120-characters]]
[cols="2v,v"]
|===
| <<All-lines-MUST-be-no-longer-than-120-characters, Rule>>
| All lines MUST be no longer than 120 characters.
|===

This is a hard limit and is enforced by the build bot. This check MUST NOT be disabled.



== Ansible


=== Ansible Yaml file extension
'''
[[All-Ansible-Yaml-files-MUST-have-a-yml-extension-and-NOT-YML-yaml-etc]]
[cols="2v,v"]
|===
| <<All-Ansible-Yaml-files-MUST-have-a-yml-extension-and-NOT-YML-yaml-etc, Rule>>
| All Ansible Yaml files MUST have a .yml extension (and NOT .YML, .yaml etc).
|===

Ansible tooling (like `ansible-galaxy init`) create files with a .yml extension. Also, the Ansible documentation website references files with a .yml extension several times. Because of this, it is normal in the Ansible community to use a .yml extension for all Ansible Yaml files.

Example: `tasks.yml`


=== Ansible CLI Variables
'''
[[Variables-meant-to-be-passed-in-from-the-ansible-CLI-MUST-have-a-prefix-of-cli]]
[cols="2v,v"]
|===
| <<Variables-meant-to-be-passed-in-from-the-ansible-CLI-MUST-have-a-prefix-of-cli, Rule>>
| Variables meant to be passed in from the ansible CLI MUST have a prefix of cli_
|===

Ansible allows variables to be passed in on the command line using the `-e` option. These variables MUST have a prefix of cli_ so that it's clear where they came from, and that they could be exploited.


.Example:
[source]
----
ansible-playbook -e cli_foo=bar someplays.yml
----

=== Ansible Global Variables
'''
[[Global-variables-MUST-have-a-prefix-of-g]]
[cols="2v,v"]
|===
| <<Global-variables-MUST-have-a-prefix-of-g, Rule>>
| Global variables MUST have a prefix of g_
|===
Ansible global variables are defined as any variables outside of ansible roles. Examples include playbook variables, variables passed in on the cli, etc.


.Example:
[source]
----
g_environment: someval
----

=== Ansible Role Variables
'''
[[Ansible-role-variable-prefix]]
[cols="2v,v"]
|===
| <<Ansible-role-variable-prefix, Rule>>
| Role variables MUST have a prefix of `r_<role_name>_`
|===

.Definition
Ansible variables contained in or passed into a role.

.Purpose
Name variables to avoid name collision between roles or playbooks.

.Example
* Role name: openshift_fooname
* Prefix: `r_openshift_fooname_`
[source,yaml]
----
r_openshift_fooname_bar_var: value_one
----
